// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccessToken(arg1) {
  return window['go']['launcher']['AccountMethod']['GetAccessToken'](arg1);
}

export function GetAccountConfig() {
  return window['go']['launcher']['AccountMethod']['GetAccountConfig']();
}

export function GetUserCode() {
  return window['go']['launcher']['AccountMethod']['GetUserCode']();
}

export function GetUserHeadSkin(arg1) {
  return window['go']['launcher']['AccountMethod']['GetUserHeadSkin'](arg1);
}

export function SetAccountConfig(arg1) {
  return window['go']['launcher']['AccountMethod']['SetAccountConfig'](arg1);
}
