// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function GetAccountConfig():Promise<launcher.ExceptionHandler_NovaPlus_module_launcher_AccountList_>;

export function SetAccountConfig(arg1:launcher.AccountList):Promise<launcher.ExceptionHandler_interface____>;
