// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccessToken(arg1) {
  return window['go']['launcher']['AccountMethod']['GetAccessToken'](arg1);
}

export function GetAccountConfig() {
  return window['go']['launcher']['AccountMethod']['GetAccountConfig']();
}

export function GetThirdAPAccessToken(arg1, arg2, arg3) {
  return window['go']['launcher']['AccountMethod']['GetThirdAPAccessToken'](arg1, arg2, arg3);
}

export function GetThirdHeadSkin(arg1, arg2) {
  return window['go']['launcher']['AccountMethod']['GetThirdHeadSkin'](arg1, arg2);
}

export function GetThirdOAuthAccessToken(arg1, arg2) {
  return window['go']['launcher']['AccountMethod']['GetThirdOAuthAccessToken'](arg1, arg2);
}

export function GetUserCode() {
  return window['go']['launcher']['AccountMethod']['GetUserCode']();
}

export function GetUserCodeThirdOAuth(arg1) {
  return window['go']['launcher']['AccountMethod']['GetUserCodeThirdOAuth'](arg1);
}

export function GetUserHeadSkin(arg1) {
  return window['go']['launcher']['AccountMethod']['GetUserHeadSkin'](arg1);
}

export function SetAccountConfig(arg1) {
  return window['go']['launcher']['AccountMethod']['SetAccountConfig'](arg1);
}
