// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function GetAccountConfig():Promise<launcher.AccountList>;

export function SetAccountConfig(arg1:launcher.AccountList):Promise<void>;
