// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartDownload(arg1, arg2) {
  return window['go']['launcher']['DownloadMethod']['StartDownload'](arg1, arg2);
}
