// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentMinecraftDir() {
  return window['go']['launcher']['LaunchMethod']['GetCurrentMinecraftDir']();
}

export function GetJavaConfig() {
  return window['go']['launcher']['LaunchMethod']['GetJavaConfig']();
}

export function GetJavaInfo(arg1) {
  return window['go']['launcher']['LaunchMethod']['GetJavaInfo'](arg1);
}

export function GetMCAllVersion(arg1) {
  return window['go']['launcher']['LaunchMethod']['GetMCAllVersion'](arg1);
}

export function GetMCVersionConfig() {
  return window['go']['launcher']['LaunchMethod']['GetMCVersionConfig']();
}

export function LaunchGame(arg1, arg2) {
  return window['go']['launcher']['LaunchMethod']['LaunchGame'](arg1, arg2);
}

export function SetJavaConfig(arg1) {
  return window['go']['launcher']['LaunchMethod']['SetJavaConfig'](arg1);
}

export function SetMCVersionConfig(arg1) {
  return window['go']['launcher']['LaunchMethod']['SetMCVersionConfig'](arg1);
}
