// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function GetCurrentMinecraftDir():Promise<string>;

export function GetJavaConfig():Promise<launcher.ExceptionHandler_NovaPlus_module_launcher_JavaConfigs_>;

export function GetJavaInfo(arg1:string):Promise<launcher.ExceptionHandler_NovaPlus_module_launcher_JavaConfig_>;

export function GetMCAllVersion(arg1:string):Promise<Array<string>>;

export function GetMCVersionConfig():Promise<launcher.ExceptionHandler_NovaPlus_module_launcher_MCConfigs_>;

export function LaunchGame(arg1:boolean,arg2:boolean):Promise<launcher.ExceptionHandler_string_>;

export function SetJavaConfig(arg1:launcher.JavaConfigs):Promise<launcher.ExceptionHandler_interface____>;

export function SetMCVersionConfig(arg1:launcher.MCConfigs):Promise<launcher.ExceptionHandler_interface____>;
