// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function GetCurrentMinecraftDir():Promise<string>;

export function GetJavaConfig():Promise<launcher.JavaConfigs>;

export function GetJavaInfo(arg1:string):Promise<launcher.JavaConfig>;

export function GetMCAllVersion(arg1:string):Promise<Array<string>>;

export function GetMCVersionConfig():Promise<launcher.MCConfigs>;

export function LaunchGame():Promise<string>;

export function SetJavaConfig(arg1:launcher.JavaConfigs):Promise<void>;

export function SetMCVersionConfig(arg1:launcher.MCConfigs):Promise<void>;
