// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBukkitUUID(arg1) {
  return window['go']['launcher']['MainMethod']['GenerateBukkitUUID'](arg1);
}

export function GetBackgroundImage(arg1) {
  return window['go']['launcher']['MainMethod']['GetBackgroundImage'](arg1);
}

export function UUIDToAvatar(arg1) {
  return window['go']['launcher']['MainMethod']['UUIDToAvatar'](arg1);
}
