// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBukkitUUID(arg1) {
  return window['go']['launcher']['MainMethod']['GenerateBukkitUUID'](arg1);
}

export function GenerateTutorialHomePage() {
  return window['go']['launcher']['MainMethod']['GenerateTutorialHomePage']();
}

export function GetAllHomePage() {
  return window['go']['launcher']['MainMethod']['GetAllHomePage']();
}

export function GetAllIPv6() {
  return window['go']['launcher']['MainMethod']['GetAllIPv6']();
}

export function GetAvailableMemory() {
  return window['go']['launcher']['MainMethod']['GetAvailableMemory']();
}

export function GetBackgroundImage(arg1) {
  return window['go']['launcher']['MainMethod']['GetBackgroundImage'](arg1);
}

export function GetJavaExecutableFileName() {
  return window['go']['launcher']['MainMethod']['GetJavaExecutableFileName']();
}

export function GetTotalMemory() {
  return window['go']['launcher']['MainMethod']['GetTotalMemory']();
}

export function ReadFile(arg1) {
  return window['go']['launcher']['MainMethod']['ReadFile'](arg1);
}

export function UUIDToAvatar(arg1) {
  return window['go']['launcher']['MainMethod']['UUIDToAvatar'](arg1);
}
