// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBukkitUUID(arg1:string):Promise<string>;

export function GetBackgroundImage(arg1:number):Promise<Array<string>>;

export function UUIDToAvatar(arg1:string):Promise<number>;
