// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function GenerateBukkitUUID(arg1:string):Promise<string>;

export function GetAllIPv6():Promise<Array<launcher.IPv6Struct>>;

export function GetAvailableMemory():Promise<number>;

export function GetBackgroundImage(arg1:number):Promise<Array<string>>;

export function GetTotalMemory():Promise<number>;

export function UUIDToAvatar(arg1:string):Promise<number>;
