// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function GenerateBukkitUUID(arg1:string):Promise<string>;

export function GenerateTutorialHomePage():Promise<void>;

export function GetAllHomePage():Promise<launcher.ExceptionHandler___NovaPlus_module_launcher_HomePageStruct_>;

export function GetAllIPv6():Promise<launcher.ExceptionHandler___NovaPlus_module_launcher_IPv6Struct_>;

export function GetArgsDir():Promise<string>;

export function GetAvailableMemory():Promise<number>;

export function GetBackgroundImage(arg1:number):Promise<Array<string>>;

export function GetJavaExecutableFileName():Promise<Array<string>>;

export function GetTotalMemory():Promise<number>;

export function Log(arg1:number,arg2:string):Promise<void>;

export function Operation():Promise<number>;

export function ReadFile(arg1:string):Promise<string>;

export function UUIDToAvatar(arg1:string):Promise<number>;

export function Version():Promise<string>;
