// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HttpCurseForge(arg1) {
  return window['go']['launcher']['Network']['HttpCurseForge'](arg1);
}

export function HttpGet(arg1, arg2) {
  return window['go']['launcher']['Network']['HttpGet'](arg1, arg2);
}

export function HttpPost(arg1, arg2, arg3) {
  return window['go']['launcher']['Network']['HttpPost'](arg1, arg2, arg3);
}
