// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigIniPath() {
  return window['go']['launcher']['ReaderWriter']['GetConfigIniPath']();
}

export function GetOtherIniPath() {
  return window['go']['launcher']['ReaderWriter']['GetOtherIniPath']();
}

export function ReadConfig(arg1, arg2, arg3) {
  return window['go']['launcher']['ReaderWriter']['ReadConfig'](arg1, arg2, arg3);
}

export function WriteConfig(arg1, arg2, arg3, arg4) {
  return window['go']['launcher']['ReaderWriter']['WriteConfig'](arg1, arg2, arg3, arg4);
}
