// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigIniPath() {
  return window['go']['launcher']['ReaderWriter']['GetConfigIniPath']();
}

export function GetCurrentExeDir() {
  return window['go']['launcher']['ReaderWriter']['GetCurrentExeDir']();
}

export function GetIsolationPath(arg1, arg2) {
  return window['go']['launcher']['ReaderWriter']['GetIsolationPath'](arg1, arg2);
}

export function GetOtherIniPath() {
  return window['go']['launcher']['ReaderWriter']['GetOtherIniPath']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['launcher']['ReaderWriter']['OpenDirectoryDialog'](arg1);
}

export function OpenExplorer(arg1) {
  return window['go']['launcher']['ReaderWriter']['OpenExplorer'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['launcher']['ReaderWriter']['OpenFileDialog'](arg1, arg2);
}

export function ReadConfig(arg1, arg2, arg3) {
  return window['go']['launcher']['ReaderWriter']['ReadConfig'](arg1, arg2, arg3);
}

export function WriteConfig(arg1, arg2, arg3, arg4) {
  return window['go']['launcher']['ReaderWriter']['WriteConfig'](arg1, arg2, arg3, arg4);
}
