// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMachineCode() {
  return window['go']['main']['App']['GetMachineCode']();
}

export function GetTodayLucky(arg1) {
  return window['go']['main']['App']['GetTodayLucky'](arg1);
}

export function StartDownload() {
  return window['go']['main']['App']['StartDownload']();
}
