// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CryptoUnlock(arg1:string):Promise<boolean>;

export function GetPCL2Identify():Promise<string>;

export function GetTodayLucky(arg1:string):Promise<number>;

export function GetUniqueAddress():Promise<string>;

export function StartDownload():Promise<void>;
