// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CryptoUnlock(arg1) {
  return window['go']['main']['App']['CryptoUnlock'](arg1);
}

export function GetPCL2Identify() {
  return window['go']['main']['App']['GetPCL2Identify']();
}

export function GetTodayLucky(arg1) {
  return window['go']['main']['App']['GetTodayLucky'](arg1);
}

export function GetUniqueAddress() {
  return window['go']['main']['App']['GetUniqueAddress']();
}

export function StartDownload() {
  return window['go']['main']['App']['StartDownload']();
}
