// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMachineCode():Promise<string>;

export function GetTodayLucky(arg1:string):Promise<number>;

export function StartDownload():Promise<void>;
